#! /bin/sh

sxhkd &
picom &
lxpolkit &
eww daemon &
gnome-keyring-daemon --start --components=pkcs11,secrets,ssh &
thunar --daemon &
~/bin/wacom.sh &
numlockx &
flameshot &
wal -R

xsetroot -cursor_name left_ptr &

bspc monitor HDMI-0 -d 1 2 3 4 5
bspc monitor DP-0 -d 6 7 8 9 10

# bspc config -m HDMI-0 top_padding 20

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Prevents focus stealing
bspc config ignore_ewmh_focus true

bspc rule -a ColorGrab state=floating


# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

eww open bar
