#! /bin/sh
bspc monitor HDMI-0 -d 1 2 3 mail chat music video
bspc monitor DP-0 -d 8 9 10

# bspc config -m HDMI-0 top_padding 20

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Prevents focus stealing
bspc config ignore_ewmh_focus true

bspc rule -a ColorGrab state=floating
bspc rule -a thunderbird desktop='^4'
bspc rule -a slack desktop='^5'
bspc rule -a discord desktop='^5'
bspc rule -a Spotify desktop='^6'
bspc rule -a zoom desktop='^7' state=floating center=on follow=on border=off


# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

# ===============
# Settings
# ===============
sxhkd &
dunst &
xsetroot -cursor_name left_ptr &
gnome-keyring-daemon --start --components=pkcs11,secrets,ssh &
lxpolkit &
DISPLAY=":0" picom -b --experimental-backends &
~/bin/wacom.sh &
wmname LG3D &
numlockx

feh --bg-fill ~/MEGA/Personal/Wallpapers/color-blur-1.jpg
wal -R

# ================
# BAR
# ================
# eww daemon &
# eww open bar &
# killall -q polybar 
polybar mainbar &
polybar secondarybar &

sleep 3

# ===============
# Apps
# ===============
thunar --daemon &
flameshot &
thunderbird &
# spotify &
